version: "2"
linters:
  default: all
  disable:
    - tagliatelle
    - depguard
    - nlreturn
    - wsl
    - wrapcheck
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
run:
  timeout: 5m
